name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create dir
        run: |
            mkdir docs
      - uses: actions/checkout@v4
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --output docs
          # install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
